name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: create env file
        env:
          MONGODB_URI_TEST: ${{ secrets.QA_ENV_FILE }}
          SECRET: ${{ secrets.PROD_ENV_FILE }}
        run: |
          touch .env
          echo MONGODB_URI_TEST=$MONGODB_URI_TEST >> .env
          echo SECRET=$SECRET >> .env
          echo PORT=3003 >> .env
          cat .env
      - name: Install dependencies
        run: npm ci
      - name: Check style
        run: npm run lint
      - name: Run Tests Vitest
        run: npm run test:vitest
      - name: Run Tests Node
        run: npm run test:node
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Tests e2e
        run: |
          npm run build &
          npm run server:test &
          npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
